export default {
  primary: "#F0B90B",
  primaryLight: "#EFE5C7",
  secondary: "#372F47",
  black: "#000",
  white: "#fff",
  gray: "#C4C4C4",
  appleColor: "#4DEEAA",
  red: "#FC1010",
  green: "#0FCB81",
  bold: "Inter-Bold",
  regular: "Inter-Regular",
  medium: "Inter-Medium",
  semiBold: "Inter-SemiBold",
  blackFont: "Inter-Black",
  extraBold: "Inter-ExtraBold",
  cavolini: "Cavolini",
};
